#!/usr/bin/env tsx

import { generateContent, isClaudeAvailable } from '../../lib/ai/claude'
import { extractTipMetadata, generateDailyTipPrompt } from '../../lib/ai/prompts/daily-tip'
import { createFileViaGitHub, generateMDXContent, generateSlug } from '../../lib/github'
import { notifyAIPublish } from '../../lib/utils/notify'

/**
 * Generates and publishes a daily development tip
 */
async function generateDailyTip(): Promise<void> {
  console.log('[Daily Tip] Starting generation...')

  if (!isClaudeAvailable()) {
    console.warn('[Daily Tip] Claude API not available. Using mock data.')
  }

  const today = new Date()
  const prompt = generateDailyTipPrompt(today)

  try {
    // Generate content using Claude
    const { content, tokensUsed } = await generateContent(prompt, {
      model: 'claude-sonnet-4-20250514',
      maxTokens: parseInt(process.env.AI_DAILY_TIP_MAX_TOKENS || '1500'),
      system: 'You are a senior software engineer writing educational content for developers.',
    })

    // Extract metadata
    const { title, summary } = extractTipMetadata(content)
    const slug = generateSlug(title)

    console.log(`[Daily Tip] Generated: "${title}" (${tokensUsed} tokens)`)

    // Generate MDX file
    const mdxContent = generateMDXContent({
      title,
      date: today,
      category: 'ai-daily-tip',
      tags: ['daily-tip', 'best-practices', 'development'],
      summary: summary || 'Daily development tip generated by AI',
      aiGenerated: true,
      content,
    })

    // Create file via GitHub API
    const filePath = `content/posts/ai-generated/daily-tip-${today.toISOString().split('T')[0]}-${slug}.mdx`

    await createFileViaGitHub({
      path: filePath,
      content: mdxContent,
      message: `chore: add daily tip "${title}"`,
    })

    console.log(`[Daily Tip] Published to: ${filePath}`)

    // Send notification
    await notifyAIPublish({
      title,
      slug,
      type: 'Daily Tip',
      tokensUsed,
    })

    console.log('[Daily Tip] ✅ Generation completed successfully')
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error)
    console.error(`[Daily Tip] Failed - date: ${today.toISOString()}, error: ${errorMessage}`)
    throw error
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateDailyTip()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error('[Daily Tip] Fatal error:', error)
      process.exit(1)
    })
}

export { generateDailyTip }
